cards = [

    {"img": "1.jpg", "type": "path", "matrix": [[0, 0, 0], [1, 1, 1], [0, 1, 0]], "gols": 0, "action": "", "player": "",
     "start": False, "finish": False},
    {"img": "2.jpg", "type": "path", "matrix": [[0, 1, 0], [1, 1, 1], [0, 0, 0]], "gols": 0, "action": "", "player": "",
     "start": False, "finish": False},
    {"img": "3.jpg", "type": "path", "matrix": [[0, 0, 0], [1, 1, 0], [0, 1, 0]], "gols": 0, "action": "", "player": "",
     "start": False, "finish": False},
    {"img": "4.jpg", "type": "path", "matrix": [[0, 1, 0], [1, 1, 0], [0, 1, 0]], "gols": 0, "action": "", "player": "",
     "start": False, "finish": False},
    {"img": "5.jpg", "type": "path", "matrix": [[0, 0, 0], [0, 1, 1], [0, 1, 0]], "gols": 0, "action": "", "player": "",
     "start": False, "finish": False},
    {"img": "6.jpg", "type": "path", "matrix": [[0, 1, 0], [1, 1, 1], [0, 1, 0]], "gols": 0, "action": "", "player": "",
     "start": False, "finish": False},
    {"img": "7.jpg", "type": "path", "matrix": [[0, 1, 0], [1, 1, 1], [0, 0, 0]], "gols": 0, "action": "", "player": "",
     "start": False, "finish": False},
    {"img": "8.jpg", "type": "path", "matrix": [[0, 1, 0], [1, 1, 1], [0, 1, 0]], "gols": 0, "action": "", "player": "",
     "start": False, "finish": False},
    {"img": "9.jpg", "type": "path", "matrix": [[0, 1, 0], [0, 1, 1], [0, 0, 0]], "gols": 0, "action": "", "player": "",
     "start": False, "finish": False},
    {"img": "10.jpg", "type": "path", "matrix": [[0, 1, 0], [1, 0, 1], [0, 1, 0]], "gols": 0, "action": "",
     "player": "", "start": False, "finish": False},

    {"img": "11.jpg", "type": "path", "matrix": [[0, 0, 0], [1, 1, 0], [0, 0, 0]], "gols": 0, "action": "",
     "player": "", "start": False, "finish": False},
    {"img": "12.jpg", "type": "path", "matrix": [[0, 0, 0], [0, 0, 1], [0, 1, 0]], "gols": 0, "action": "",
     "player": "", "start": False, "finish": False},
    {"img": "13.jpg", "type": "path", "matrix": [[0, 1, 0], [1, 0, 0], [0, 0, 0]], "gols": 0, "action": "",
     "player": "", "start": False, "finish": False},
    {"img": "14.jpg", "type": "path", "matrix": [[0, 0, 0], [0, 1, 1], [0, 0, 0]], "gols": 0, "action": "",
     "player": "", "start": False, "finish": False},
    {"img": "15.jpg", "type": "path", "matrix": [[0, 1, 0], [1, 0, 1], [0, 1, 0]], "gols": 0, "action": "",
     "player": "", "start": False, "finish": False},
    {"img": "16.jpg", "type": "path", "matrix": [[0, 0, 0], [1, 1, 0], [0, 1, 0]], "gols": 0, "action": "",
     "player": "", "start": False, "finish": False},
    {"img": "17.jpg", "type": "path", "matrix": [[0, 1, 0], [1, 1, 1], [0, 1, 0]], "gols": 0, "action": "",
     "player": "", "start": False, "finish": False},
    {"img": "18.jpg", "type": "path", "matrix": [[0, 0, 0], [1, 1, 1], [0, 1, 0]], "gols": 0, "action": "",
     "player": "", "start": False, "finish": False},
    {"img": "19.jpg", "type": "path", "matrix": [[0, 1, 0], [1, 1, 1], [0, 1, 0]], "gols": 0, "action": "",
     "player": "", "start": False, "finish": False},
    {"img": "20.jpg", "type": "path", "matrix": [[0, 1, 0], [1, 1, 0], [0, 0, 0]], "gols": 0, "action": "",
     "player": "", "start": False, "finish": False},

    {"img": "21.jpg", "type": "path", "matrix": [[0, 1, 0], [0, 1, 1], [0, 1, 0]], "gols": 0, "action": "",
     "player": "", "start": False, "finish": False},
    {"img": "22.jpg", "type": "path", "matrix": [[0, 1, 0], [0, 1, 1], [0, 0, 0]], "gols": 0, "action": "",
     "player": "", "start": False, "finish": False},
    {"img": "23.jpg", "type": "path", "matrix": [[0, 0, 0], [1, 1, 1], [0, 1, 0]], "gols": 0, "action": "",
     "player": "", "start": False, "finish": False},
    {"img": "24.jpg", "type": "path", "matrix": [[0, 1, 0], [1, 1, 1], [0, 0, 0]], "gols": 0, "action": "",
     "player": "", "start": False, "finish": False},
    {"img": "25.jpg", "type": "path", "matrix": [[0, 0, 0], [1, 0, 1], [0, 1, 0]], "gols": 0, "action": "",
     "player": "", "start": False, "finish": False},
    {"img": "26.jpg", "type": "path", "matrix": [[0, 1, 0], [0, 1, 0], [0, 1, 0]], "gols": 0, "action": "",
     "player": "", "start": False, "finish": False},
    {"img": "27.jpg", "type": "path", "matrix": [[0, 0, 0], [0, 1, 1], [0, 1, 0]], "gols": 0, "action": "",
     "player": "", "start": False, "finish": False},
    {"img": "28.jpg", "type": "path", "matrix": [[0, 1, 0], [0, 1, 1], [0, 1, 0]], "gols": 0, "action": "",
     "player": "", "start": False, "finish": False},
    {"img": "29.jpg", "type": "path", "matrix": [[0, 0, 0], [1, 1, 1], [0, 0, 0]], "gols": 0, "action": "",
     "player": "", "start": False, "finish": False},
    {"img": "30.jpg", "type": "path", "matrix": [[0, 1, 0], [0, 1, 0], [0, 1, 0]], "gols": 0, "action": "",
     "player": "", "start": False, "finish": False},

    {"img": "31.jpg", "type": "path", "matrix": [[0, 0, 0], [0, 1, 1], [0, 1, 0]], "gols": 0, "action": "",
     "player": "", "start": False, "finish": False},
    {"img": "32.jpg", "type": "path", "matrix": [[0, 1, 0], [0, 1, 1], [0, 0, 0]], "gols": 0, "action": "",
     "player": "", "start": False, "finish": False},
    {"img": "33.jpg", "type": "path", "matrix": [[0, 1, 0], [0, 1, 0], [0, 0, 0]], "gols": 0, "action": "",
     "player": "", "start": False, "finish": False},
    {"img": "34.jpg", "type": "path", "matrix": [[0, 1, 0], [1, 1, 0], [0, 0, 0]], "gols": 0, "action": "",
     "player": "", "start": False, "finish": False},
    {"img": "35.jpg", "type": "path", "matrix": [[0, 1, 0], [1, 1, 1], [0, 0, 0]], "gols": 0, "action": "",
     "player": "", "start": False, "finish": False},
    {"img": "36.jpg", "type": "path", "matrix": [[0, 0, 0], [0, 1, 1], [0, 1, 0]], "gols": 0, "action": "",
     "player": "", "start": False, "finish": False},
    {"img": "37.jpg", "type": "path", "matrix": [[0, 1, 0], [0, 1, 1], [0, 1, 0]], "gols": 0, "action": "",
     "player": "", "start": False, "finish": False},
    {"img": "38.jpg", "type": "path", "matrix": [[0, 1, 0], [0, 1, 1], [0, 0, 0]], "gols": 0, "action": "",
     "player": "", "start": False, "finish": False},
    {"img": "39.jpg", "type": "path", "matrix": [[0, 1, 0], [0, 1, 0], [0, 1, 0]], "gols": 0, "action": "",
     "player": "", "start": False, "finish": False},
    {"img": "40.jpg", "type": "path", "matrix": [[0, 1, 0], [0, 0, 0], [0, 1, 0]], "gols": 0, "action": "",
     "player": "", "start": False, "finish": False},

    {"img": "41.jpg", "type": "path", "matrix": [[0, 1, 0], [1, 1, 1], [0, 1, 0]], "gols": 0, "action": "",
     "player": "", "start": False, "finish": False},
    {"img": "42.jpg", "type": "path", "matrix": [[0, 1, 0], [1, 1, 1], [0, 1, 0]], "gols": 0, "action": "",
     "player": "", "start": False, "finish": False},
    {"img": "43.jpg", "type": "path", "matrix": [[0, 0, 0], [1, 0, 0], [0, 1, 0]], "gols": 0, "action": "",
     "player": "", "start": False, "finish": False},
    {"img": "44.jpg", "type": "path", "matrix": [[0, 1, 0], [0, 1, 1], [0, 0, 0]], "gols": 0, "action": "",
     "player": "", "start": False, "finish": False},

    {"img": "map1.jpg", "type": "action", "matrix": [], "gols": 0, "action": "see_map", "player": "", "start": False,
     "finish": False},
    {"img": "map1.jpg", "type": "action", "matrix": [], "gols": 0, "action": "see_map", "player": "", "start": False,
     "finish": False},
    {"img": "map1.jpg", "type": "action", "matrix": [], "gols": 0, "action": "see_map", "player": "", "start": False,
     "finish": False},
    {"img": "map1.jpg", "type": "action", "matrix": [], "gols": 0, "action": "see_map", "player": "", "start": False,
     "finish": False},
    {"img": "map1.jpg", "type": "action", "matrix": [], "gols": 0, "action": "see_map", "player": "", "start": False,
     "finish": False},
    {"img": "map1.jpg", "type": "action", "matrix": [], "gols": 0, "action": "see_map", "player": "", "start": False,
     "finish": False},

    {"img": "rockfall.jpeg", "type": "action", "matrix": [], "gols": 0, "action": "rockfall", "player": "",
     "start": False, "finish": False},
    {"img": "rockfall.jpeg", "type": "action", "matrix": [], "gols": 0, "action": "rockfall", "player": "",
     "start": False, "finish": False},
    {"img": "rockfall.jpeg", "type": "action", "matrix": [], "gols": 0, "action": "rockfall", "player": "",
     "start": False, "finish": False},
    {"img": "break_pickaxe.jpeg", "type": "action", "matrix": [], "gols": 0, "action": "break_pickaxe", "player": "",
     "start": False, "finish": False},
    {"img": "break_pickaxe.jpeg", "type": "action", "matrix": [], "gols": 0, "action": "break_pickaxe", "player": "",
     "start": False, "finish": False},
    {"img": "break_pickaxe.jpeg", "type": "action", "matrix": [], "gols": 0, "action": "break_pickaxe", "player": "",
     "start": False, "finish": False},
    {"img": "break_lantern.jpeg", "type": "action", "matrix": [], "gols": 0, "action": "break_lantern", "player": "",
     "start": False, "finish": False},
    {"img": "break_lantern.jpeg", "type": "action", "matrix": [], "gols": 0, "action": "break_lantern", "player": "",
     "start": False, "finish": False},
    {"img": "break_lantern.jpeg", "type": "action", "matrix": [], "gols": 0, "action": "break_lantern", "player": "",
     "start": False, "finish": False},
    {"img": "break_cart.png", "type": "action", "matrix": [], "gols": 0, "action": "break_cart", "player": "",
     "start": False, "finish": False},
    {"img": "break_cart.png", "type": "action", "matrix": [], "gols": 0, "action": "break_cart", "player": "",
     "start": False, "finish": False},
    {"img": "break_cart.png", "type": "action", "matrix": [], "gols": 0, "action": "break_cart", "player": "",
     "start": False, "finish": False},
    {"img": "fix_pickaxe.jpg", "type": "action", "matrix": [], "gols": 0, "action": "fix_pickaxe", "player": "",
     "start": False, "finish": False},
    {"img": "fix_pickaxe.jpg", "type": "action", "matrix": [], "gols": 0, "action": "fix_pickaxe", "player": "",
     "start": False, "finish": False},

    {"img": "fix_lantern.jpg", "type": "action", "matrix": [], "gols": 0, "action": "fix_lantern", "player": "",
     "start": False, "finish": False},
    {"img": "fix_lantern.jpg", "type": "action", "matrix": [], "gols": 0, "action": "fix_lantern", "player": "",
     "start": False, "finish": False},
    {"img": "fix_cart.jpg", "type": "action", "matrix": [], "gols": 0, "action": "fix_cart", "player": "",
     "start": False, "finish": False},
    {"img": "fix_cart.jpg", "type": "action", "matrix": [], "gols": 0, "action": "fix_cart", "player": "",
     "start": False, "finish": False},

    {"img": "dual_pickaxe_lantern.jpg", "type": "action", "matrix": [], "gols": 0, "action": "dual_pickaxe_lantern",
     "player": "", "start": False, "finish": False},
    {"img": "dual_pickaxe_cart.jpg", "type": "action", "matrix": [], "gols": 0, "action": "dual_pickaxe_cart",
     "player": "", "start": False, "finish": False},
    {"img": "dual_lantern_cart.jpg", "type": "action", "matrix": [], "gols": 0, "action": "dual_lantern_cart",
     "player": "", "start": False, "finish": False}

]
